### ISSUE TITLE
Skype ad-blocking

### ISSUE THREAD

**Issue by kapoios** [darugnaa/dns#1]
Not really an issue just FYI, IMHO there's no need to block all these domains to block Skype ads. Blocking just apps.skype.com works like a charm for me, about 2-3 years now, no need to block any other domains. The only side effect is that "Skype home" and Facebook integration break after this, but everything else works fine.

**Comment by darugnaa** [comment]
I noticed that blocking those domains do not work anymore.
I'll try your suggestion and edit accordingly. _Skype Home_ and _Facebook Integration_ are useless to me, better if they don't show up.
Thank you :-)

**Comment by darugnaa** [comment]
Added some more hosts to block. Works with recent skype 7.27.
