### ISSUE TITLE
Block Taboola ads

### ISSUE THREAD

**Issue by cbwee** [darugnaa/dns#5]
Taboola ads appear in Microsoft Edge's news, and also in Microsoft Minesweeper, so these domains should be add to block those ads.

`# Block Taboola ads`
`0.0.0.0 popup.taboola.com`
`0.0.0.0 www.popup.taboola.com`
`0.0.0.0 taboola.com`
`0.0.0.0 www.taboola.com`
`0.0.0.0 cdn.taboolasyndication.com`
`0.0.0.0 taboolasyndication.com`
`0.0.0.0 www.taboolasyndication.com`
`0.0.0.0 www.cdn.taboolasyndication.com`
`0.0.0.0 trc.taboola.com`
`0.0.0.0 www.trc.taboola.com`
`0.0.0.0 images.taboola.com`
`0.0.0.0 www.images.taboola.com`
`0.0.0.0 adserver.adtechus.com`
`0.0.0.0 www.adserver.adtechus.com`
`0.0.0.0 us-u.openx.net`
`0.0.0.0 www.us-u.openx.net`
`0.0.0.0 api.taboola.com`
`0.0.0.0 www.api.taboola.com`
`0.0.0.0 c2.taboola.com`
`0.0.0.0 www.c2.taboola.com`
`0.0.0.0 cdn.taboola.com`
`0.0.0.0 www.cdn.taboola.com`
`0.0.0.0 urc.taboolasyndication.com`
`0.0.0.0 www.urc.taboolasyndication.com`
`0.0.0.0 taboola.com.edgekey.net`
`0.0.0.0 www.taboola.com.edgekey.net`
`0.0.0.0 esd-secure.taboola.com.edgekey.net`
`0.0.0.0 www.esd-secure.taboola.com.edgekey.net`
`0.0.0.0 api.taboola.com`
`0.0.0.0 c2.taboola.com`
`0.0.0.0 cdn.taboola.com`
`0.0.0.0 urc.taboolasyndication.com`
`0.0.0.0 taboola.com.edgekey.net`
`0.0.0.0 esd-secure.taboola.com.edgekey.net`
`0.0.0.0 imprlatbmp.taboola.com`
`0.0.0.0 api-s2s.taboola.com`
`0.0.0.0 wf.taboola.com`
`0.0.0.0 convlatbmp.taboola.com`
`0.0.0.0 15.taboola.com`
`0.0.0.0 vidstat.taboola.com`
`0.0.0.0 img.img-taboola.com`

`# Microsoft Edge ads and tracking`
`0.0.0.0 srtb.msn.com`
`0.0.0.0 c.msn.com`
`0.0.0.0 contextual.media.net`
`0.0.0.0 web.vortex.data.msn.com`
`0.0.0.0 sb.scorecardresearch.com`
`0.0.0.0 c.bing.com`
`0.0.0.0 ssl.google-analytics.com`
`0.0.0.0 www.google-analytics.com`
`0.0.0.0 marketingplatform.google.com`
`0.0.0.0 staging.pango-coupons.besttoolbars.net`

Some are taken from https://gist.github.com/iturgeon/b558ca84907e7dfc42ff42e57a3aff73, and I found the other ones using NextDNS.

**Comment by cbwee** [comment]
I have just found more tracking and ad domains that Microsoft Edge's news page uses, I have added them above.

**Comment by darugnaa** [comment]
Thanks for the suggestion! I am using https://pi-hole.net/ instead of maintaining a local file
